### ISSUE TITLE
cityPicker.show()方法的时候崩溃

### ISSUE THREAD

**Issue by lucklyperson** [crazyandcoder/citypicker#22]
CityPicker cityPicker = new CityPicker.Builder(AuthActivity.this)
                .textSize(13)
                .title("选择居住地")
                .backgroundPop(0xa0000000)
                .titleBackgroundColor("#234Dfa")
                .titleTextColor("#000000")
                .backgroundPop(0xa0000000)
                .confirTextColor("#000000")
                .cancelTextColor("#000000")
                .province("江苏省")
                .city("常州市")
                .district("天宁区")
                .textColor(Color.parseColor("#000000"))
                .provinceCyclic(true)
                .cityCyclic(true)
                .districtCyclic(true)
                .visibleItemsCount(7)
                .itemPadding(10)
                .onlyShowProvinceAndCity(false)
                .build();
        cityPicker.show();
前面都没问题，执行.show方法的时候崩溃。是不是获取数据失败。

**Comment by crazyandcoder** [comment]
把log贴出来看看

**Comment by lucklyone** [comment]
错误 : java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shaodianbao/com.shaodianbao.ui.SetActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running? at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331) at android.app.ActivityThread.access$1000(ActivityThread.java:143) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5291) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665) at dalvik.system.NativeStart.main(Native Method) Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running? at android.view.ViewRootImpl.setView(ViewRootImpl.java:582) at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:269) at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69) at android.widget.PopupWindow.invokePopup(PopupWindow.java:1025) at android.widget.PopupWindow.showAtLocation(PopupWindow.java:853) at android.widget.PopupWindow.showAtLocation(PopupWindow.java:817) at com.lljjcoder.citypickerview.widget.CityPicker.show(CityPicker.java:822) at com.shaodianbao.ui.SetActivity.initView(SetActivity.java:83) at com.shaodianbao.ui.SetActivity.onCreate(SetActivity.java:54) at android.app.Activity.performCreate(Activity.java:5304) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245) ... 11 more android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running? at android.view.ViewRootImpl.setView(ViewRootImpl.java:582) at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:269) at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69) at android.widget.PopupWindow.invokePopup(PopupWindow.java:1025) at android.widget.PopupWindow.showAtLocation(PopupWindow.java:853) at android.widget.PopupWindow.showAtLocation(PopupWindow.java:817) at com.lljjcoder.citypickerview.widget.CityPicker.show(CityPicker.java:822) at com.shaodianbao.ui.SetActivity.initView(SetActivity.java:83) at com.shaodianbao.ui.SetActivity.onCreate(SetActivity.java:54) at android.app.Activity.performCreate(Activity.java:5304) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331) at android.app.ActivityThread.access$1000(ActivityThread.java:143) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5291) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665) at dalvik.system.NativeStart.main(Native Method)

**Comment by crazyandcoder** [comment]
这个error很简单，就是说你的SetActivity还没完全初始化完成就添加这个Citypicker了，因为CityPicker是个popWindow，没有Activity进行依赖的话就会报Unable to add window -- token null is not valid这个错！

**Comment by lucklyone** [comment]
但是怎么会出现还没初始化完成，这个Activity里面也没有什么耗时操作。我都放到onResume里还是报错。

**Comment by lucklyone** [comment]
解决了，把它放在点击事件里就可以了。刚开始放在onCreate，onResume都会报错。单独抽成个方法用的时候才进行初始化。
